"""Dealz class updated (price_in_cents)

Revision ID: 04d9b2b00358
Revises: 80eea344384b
Create Date: 2025-11-22 12:02:12.000019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04d9b2b00358'
down_revision: Union[str, Sequence[str], None] = '80eea344384b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricehistory', sa.Column('price_in_cents', sa.Integer(), nullable=False))
    op.drop_column('pricehistory', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricehistory', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pricehistory', 'price_in_cents')
    # ### end Alembic commands ###
