"""Add new entry to Dealz class (currency)

Revision ID: 0ca580b7bcbe
Revises: 71774867194d
Create Date: 2025-11-21 18:21:03.287388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0ca580b7bcbe"
down_revision: Union[str, Sequence[str], None] = "71774867194d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dealz",
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "dealz", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "dealz", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dealz", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "dealz", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("dealz", "currency")
    # ### end Alembic commands ###
