"""PriceHistory class updated (created_at)

Revision ID: 80eea344384b
Revises: de67015dc3e7
Create Date: 2025-11-21 19:11:55.174157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80eea344384b'
down_revision: Union[str, Sequence[str], None] = 'de67015dc3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricehistory', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('pricehistory', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricehistory', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('pricehistory', 'created_at')
    # ### end Alembic commands ###
