"""Add new entry to Dealz class (url, merchant)

Revision ID: 812c5ef3bbcd
Revises: 0ca580b7bcbe
Create Date: 2025-11-21 18:31:37.960621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '812c5ef3bbcd'
down_revision: Union[str, Sequence[str], None] = '0ca580b7bcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealz', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dealz', sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealz', 'merchant')
    op.drop_column('dealz', 'url')
    # ### end Alembic commands ###
