"""Added PriceHistory class to database

Revision ID: de67015dc3e7
Revises: 605f73f1e94a
Create Date: 2025-11-21 19:07:02.865402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de67015dc3e7'
down_revision: Union[str, Sequence[str], None] = '605f73f1e94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealz', sa.Column('lowest_price', sa.Integer(), nullable=True))
    op.drop_column('dealz', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealz', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dealz', 'lowest_price')
    # ### end Alembic commands ###
