"""Dealz class updated

Revision ID: f355b76d11a3
Revises: 91368e7d7470
Create Date: 2025-11-22 12:33:35.465333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f355b76d11a3'
down_revision: Union[str, Sequence[str], None] = '91368e7d7470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricehistory', 'price_in_cents',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricehistory', 'price_in_cents',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
